interface ErrorCodes {[key: string]: string};

export const authErrors: ErrorCodes = {
    "admin-restricted-operation": "Restricted to administrators only.",
    "argument-error": "",
    "app-not-authorized": "App not authorized for Firebase Authentication.",
    "app-not-installed": "Mobile app not installed on this device.",
    "captcha-check-failed": "Invalid reCAPTCHA response.",
    "code-expired": "SMS code expired.",
    "cordova-not-ready": "Cordova framework not ready.",
    "cors-unsupported": "Browser not supported.",
    "credential-already-in-use": "Credential already in use.",
    "custom-token-mismatch": "Custom token mismatch.",
    "requires-recent-login": "Requires recent authentication.",
    "dynamic-link-not-activated": "Dynamic Links not activated.",
    "email-change-needs-verification": "Email change needs verification.",
    "email-already-in-use": "Email already in use.",
    "expired-action-code": "Expired action code.",
    "cancelled-popup-request": "Cancelled popup request.",
    "internal-error": "Internal error.",
    "invalid-app-credential": "Invalid app credential.",
    "invalid-app-id": "Invalid mobile app identifier.",
    "invalid-user-token": "Invalid user's credential.",
    "invalid-auth-event": "Internal error occurred.",
    "invalid-verification-code": "Invalid SMS verification code.",
    "invalid-continue-uri": "Invalid continue URL.",
    "invalid-cordova-configuration": "Invalid Cordova configuration.",
    "invalid-custom-token": "Invalid custom token format.",
    "invalid-dynamic-link-domain": "Invalid dynamic link domain.",
    "invalid-email": "Invalid email address format.",
    "invalid-api-key": "Invalid API key.",
    "invalid-cert-hash": "Invalid SHA-1 certificate hash.",
    "invalid-credential": "Invalid auth credential.",
    "invalid-message-payload": "Invalid email template.",
    "invalid-multi-factor-session": "Invalid multi-factor session.",
    "invalid-oauth-provider": "Invalid OAuth provider.",
    "invalid-oauth-client-id": "Invalid OAuth client ID.",
    "unauthorized-domain": "Unauthorized domain for OAuth operations.",
    "invalid-action-code": "Invalid action code.",
    "wrong-password": "Invalid password.",
    "invalid-persistence-type": "Invalid persistence type.",
    "invalid-phone-number": "Invalid phone number format.",
    "invalid-provider-id": "Invalid provider ID.",
    "invalid-recipient-email": "Invalid recipient email.",
    "invalid-sender": "Invalid sender email or name.",
    "invalid-verification-id": "Invalid verification ID.",
    "invalid-tenant-id": "Invalid tenant ID.",
    "multi-factor-info-not-found": "No second factor found.",
    "multi-factor-auth-required": "Second factor required.",
    "missing-android-pkg-name": "Missing Android package name.",
    "auth-domain-config-required": "Auth domain configuration required.",
    "missing-app-credential": "Missing app credential.",
    "missing-verification-code": "Missing verification code.",
    "missing-continue-uri": "Missing continue URL.",
    "missing-iframe-start": "Internal error occurred.",
    "missing-ios-bundle-id": "Missing iOS Bundle ID.",
    "missing-multi-factor-info": "Missing multi-factor info.",
    "missing-multi-factor-session": "Missing multi-factor session proof.",
    "missing-or-invalid-nonce": "Missing or invalid nonce.",
    "missing-phone-number": "Missing phone number.",
    "missing-verification-id": "Missing verification ID.",
    "app-deleted": "FirebaseApp instance deleted.",
    "account-exists-with-different-credential": "Account exists with different credentials.",
    "network-request-failed": "Network request failed.",
    "no-auth-event": "Internal error occurred.",
    "no-such-provider": "Provider not linked to user.",
    "null-user": "Null user object provided.",
    "operation-not-allowed": "Sign-in provider disabled.",
    "operation-not-supported-in-this-environment": "Operation not supported in this environment.",
    "popup-blocked": "Popup blocked by browser.",
    "popup-closed-by-user": "Popup closed by user.",
    "provider-already-linked": "Provider already linked to user.",
    "quota-exceeded": "Quota exceeded.",
    "redirect-cancelled-by-user": "Redirect cancelled by user.",
    "redirect-operation-pending": "Redirect operation pending.",
    "rejected-credential": "Rejected credential.",
    "second-factor-already-in-use": "Second factor already in use.",
    "maximum-second-factor-count-exceeded": "Maximum second factors exceeded.",
    "tenant-id-mismatch": "Tenant ID mismatch.",
    "timeout": "Operation timed out.",
    "user-token-expired": "User's credential expired.",
    "too-many-requests": "Too many requests.",
    "unauthorized-continue-uri": "Unauthorized continue URL.",
    "unsupported-first-factor": "Unsupported first factor.",
    "unsupported-persistence-type": "Unsupported persistence type.",
    "unsupported-tenant-operation": "Unsupported operation in multi-tenant context.",
    "unverified-email": "Operation requires verified email.",
    "user-cancelled": "User cancelled permission request.",
    "user-not-found": "User not found.",
    "user-disabled": "User account disabled by administrator.",
    "user-mismatch": "Credentials do not match signed-in user.",
    "user-signed-out": "",
    "weak-password": "Weak password.",
    "web-storage-unsupported": "Unsupported browser or disabled cookies.",
  };
  